# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71702d692a069e780d6c019ba64f1f608d9a55951052ed4f3492ccf8e1b9104953669e1b1f76f78c4834464958588d3446cc6b2b10aeb67154565a3f597d7f26

test:
  secret_key_base: 9361dd51f08004574cd9fc8426017d3a729cdb253ac28d9e764ba69d668a8e1ce07803dc232c678b5cd36161616edbbb02b5ef42dd6b9b185d83f6dfe3f92252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
